Update delugePostProcess.py
Change os.rmdir to os.removedirs to avoid:
Traceback (most recent call last):
  File "/opt/automator/delugePostProcess.py", line 142, in <module>
    os.rmdir(delete_dir)
OSError: [Errno 39] Directory not empty: